version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app
    container_name: react-app
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000

